#!/bin/bash
FACTOR=${1}
BASE_WIDTH=1920

if [ "${FACTOR}"X == X ];
then
	echo "please provide a scale factor"
	exit 1
fi

if [ "${FACTOR}" == "1" ] || [ "${FACTOR}" == "2" ];
then
	xrandr --output DP-3 --scale ${FACTOR}x${FACTOR} --pos 0x0 \
		--output HDMI-0 --scale ${FACTOR}x${FACTOR} --auto --pos $((${BASE_WIDTH} * ${FACTOR}))x0
	
else 
	echo "invalid factor given: valid 1,2"
	exit 2
fi
