#!/bin/sh

bspc monitor DP-3 -d I
bspc monitor HDMI-0 -d II

bspc config border_width        0
bspc config window_gap          0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config bottom_padding      0
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config window_gap          0

bspc rule -a 'Firefox' desktop='^2'
bspc rule -a 'nvim-qt' desktop='^1'

bspc rule -a 'fetch-clock' desktop='^1' sticky=on state=floating rectangle=10x100

#firefox &
#nvim-qt &
